api:
  image: platform-api
  tag: v4
  pullPolicy: IfNotPresent

dashboard:
  image: platform-dashboard
  tag: v8
  pullPolicy: IfNotPresent


ingress:
  dashboardHost: platform-dashboard.localtest.me
  apiHost: platform.localtest.me
  className: nginx
