apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-api-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-api-cr
rules:
  # cluster-scoped
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create", "delete"]

  # core namespaced resources
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - secrets
      - configmaps
      - events
      - serviceaccounts
      - resourcequotas
      - limitranges
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

  # apps resources
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - replicasets
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

  # networking resources
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - ingressclasses
      - networkpolicies
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

  # policy resources
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

  
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-api-crb
subjects:
  - kind: ServiceAccount
    name: platform-api-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: platform-api-cr
  apiGroup: rbac.authorization.k8s.io
